### ISSUE TITLE
fixing plot_cxctime markers in ska3-next

### ISSUE THREAD

**Issue by jeanconn** [sot/Ska.Matplotlib#22]
With regard to what we actually want, I reviewed #21 in the context of "Since the default 'C0' is also blue and the default linestyle is -, I don't think it would completely break any plots to just change the default fmt to None and not pass it through if None. I suspect that everyone that notices color will be thrilled at this change."  and I thought the change as written there accomplished that.. and that we'd gotten a bit of community buy-in on slack. 
I suppose part of my "let's just approve it" in that context was based on the idea that I thought we wanted to get it quickly into a candidate to have more community review.  

But it sounds like there was a tiny misunderstanding about handling of defaults in that the default for matplotlib's plot_date seems to have fmt='o', so it sounds like we either want to override that with a not-None fmt in plot_cxctime or we want to set it the marker default in plot_cxctime with 'marker'.  Am I understanding correctly?

What is the test array that you'd like to see in a new change to repair the defaults @taldcroft ?

**Comment by taldcroft** [comment]
> I thought the change as written there accomplished that..

And I had thought so as well, so this highlights then need to be vigilant with functional testing to actually verify our expectations when there are no unit tests.

Here is a start on the test array, plot_cxctime with args/kwargs. In each case the new should match the old except for the default color being `C0` instead of `b`.
```
(t, y)
(t, y, marker='o', color='C1')
(t, y, marker='o', linestyle='--', color='C1')
(t, y, '-b', marker='o', linestyle='--', color='C1')  # Warnings OK
(t, y, '-b', color='C1')  # Warnings OK
(t, y, fmt='-b', color='C1')  # Warnings OK
(t, y, '--g')
```

**Comment by javierggt** [comment]
Quick question, @taldcroft: why do you keep writing `C0`? That does not appear as any of the named colors. This blue is `tab:blue`.

Are `C0`, `C1`, etc shorthands for the cycle colors?

**Comment by jeanconn** [comment]
I think I can take that question... https://matplotlib.org/stable/tutorials/colors/colors.html#cn-color-selection ?

So I think yes, shorthands for the cycle colors.  Though I do interpret that to mean that `C0` isn't necessarily `tab:blue` depending on the styler/cycle.
